### ISSUE TITLE
problem: No wrong happened.  But I cannot see any motors.

### ISSUE THREAD

**Issue by LIANGXINKAI** [mit-acl/aclswarm#3]
Thanks for your fantastic work. But I meet One problem:
When I click start, the RViz and rqt pop out like in the picture, but I could not see any motors, like that
![Screenshot from 2020-12-14 18-44-54](https://user-images.githubusercontent.com/22145345/102072685-2d5e1600-3e3d-11eb-8cce-40a704ad8b33.png)

**Comment by plusk01** [comment]
Hi @LIANGXINKAI, 

This is what I see after running `rosrun aclswarm_sim trials.sh -f swarm6_3d -i`

![image](https://user-images.githubusercontent.com/3934603/103417705-c4271400-4b59-11eb-8db1-e0e2034c527e.png)

And this is what it looks like after running `rosrun aclswarm_sim trials.sh -f simform20 -i`

![image](https://user-images.githubusercontent.com/3934603/103417755-00f30b00-4b5a-11eb-84cd-81c51e227d44.png)

Two suggestions:
1. Does `rosrun aclswarm_sim trials.sh -f swarm6_3d -i` work as expected?
2. I notice in your rviz that it says `No tf data` --- it may be that something didn't start correctly. For the `swarm6_3d` formation, my `rqt_graph` looks like the following (showing only two of the simulated vehicles):

![image](https://user-images.githubusercontent.com/3934603/103417861-69da8300-4b5a-11eb-9ae9-2f1c7de6d65c.png)

**Comment by plusk01** [comment]
closing for now, feel free to reopen if you are still facing this issue

**Comment by YM-98** [comment]
Hello, I encountered the same problem, the terminal does not report an error ,but RVIZ does not display the model, and my rqt_graph shows few nodes, I don't know how to deal with it, hope you can help me.
![2022-11-01_15-55](https://user-images.githubusercontent.com/95565327/199185879-9aa66350-fd71-428e-9eba-2c53d4ca2299.png)
![2022-11-01_15-56](https://user-images.githubusercontent.com/95565327/199185885-a3334a64-51c8-4526-8f00-427e49672a35.png)

**Comment by plusk01** [comment]
hi @YM-98  please consider opening a new issue instead of adding to this closed, different issue.

What command did you run? Your `rqt_graph` only shows the `operator` node running, so the actual distributed swarm pipeline did not run.

**Comment by yi11122** [comment]
tmux should be installed first

**Comment by yi11122** [comment]
and add the workspace setup.bash into the .bashrc
